name: deploy

on:
  push:
    branches:
      - main  # または対象のブランチ名
    paths:
      - 'prototype/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: prototype

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install Dependencies
        run: npm install
        working-directory: ${{ env.WORKING_DIR }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.WORKING_DIR }}

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS s3 sync"
          aws s3 sync --region ap-northeast-1 ./${{ env.WORKING_DIR }}/out s3://${{ secrets.AWS_S3_BUCKET }} --delete
